name: External Integration

on:
  push:
    branches:
      -  main

jobs:
  external-notification:
    runs-on: ubuntu-latest

  steps:
    - name: Notifcation via curl base request
      run: curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"text":"Hello from GitHub Actions! from Raj 🚀"}' \
  "${{ secret.WEBHOOK }}"
